/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as AuthedIndexRouteImport } from './routes/_authed.index'
import { Route as AuthedTrainingRouteImport } from './routes/_authed.training'
import { Route as AuthedLabRouteImport } from './routes/_authed.lab'
import { Route as AuthedExamRouteImport } from './routes/_authed.exam'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedIndexRoute = AuthedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedTrainingRoute = AuthedTrainingRouteImport.update({
  id: '/training',
  path: '/training',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedLabRoute = AuthedLabRouteImport.update({
  id: '/lab',
  path: '/lab',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedExamRoute = AuthedExamRouteImport.update({
  id: '/exam',
  path: '/exam',
  getParentRoute: () => AuthedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthedIndexRoute
  '/login': typeof LoginRoute
  '/exam': typeof AuthedExamRoute
  '/lab': typeof AuthedLabRoute
  '/training': typeof AuthedTrainingRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/exam': typeof AuthedExamRoute
  '/lab': typeof AuthedLabRoute
  '/training': typeof AuthedTrainingRoute
  '/': typeof AuthedIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authed': typeof AuthedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authed/exam': typeof AuthedExamRoute
  '/_authed/lab': typeof AuthedLabRoute
  '/_authed/training': typeof AuthedTrainingRoute
  '/_authed/': typeof AuthedIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/login' | '/exam' | '/lab' | '/training'
  fileRoutesByTo: FileRoutesByTo
  to: '/login' | '/exam' | '/lab' | '/training' | '/'
  id:
    | '__root__'
    | '/_authed'
    | '/login'
    | '/_authed/exam'
    | '/_authed/lab'
    | '/_authed/training'
    | '/_authed/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthedRoute: typeof AuthedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/': {
      id: '/_authed/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthedIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/training': {
      id: '/_authed/training'
      path: '/training'
      fullPath: '/training'
      preLoaderRoute: typeof AuthedTrainingRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/lab': {
      id: '/_authed/lab'
      path: '/lab'
      fullPath: '/lab'
      preLoaderRoute: typeof AuthedLabRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/exam': {
      id: '/_authed/exam'
      path: '/exam'
      fullPath: '/exam'
      preLoaderRoute: typeof AuthedExamRouteImport
      parentRoute: typeof AuthedRoute
    }
  }
}

interface AuthedRouteChildren {
  AuthedExamRoute: typeof AuthedExamRoute
  AuthedLabRoute: typeof AuthedLabRoute
  AuthedTrainingRoute: typeof AuthedTrainingRoute
  AuthedIndexRoute: typeof AuthedIndexRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedExamRoute: AuthedExamRoute,
  AuthedLabRoute: AuthedLabRoute,
  AuthedTrainingRoute: AuthedTrainingRoute,
  AuthedIndexRoute: AuthedIndexRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthedRoute: AuthedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
